In [2]:
import pandas as pd

In [3]:
raw_df = pd.read_csv('Copy of Online Retail.csv')

In [4]:
df = raw_df.copy()

In [5]:
print("Original dataset shape:", raw_df.shape)
print("Working copy shape:", df.shape)

print("Datasets identical:", raw_df.equals(df))

Original dataset shape: (541909, 8)
Working copy shape: (541909, 8)
Datasets identical: True

In [6]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [8]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [9]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(5268)

In [11]:
df['InvoiceNo'].astype(str).str.startswith('C').sum()

np.int64(9288)

In [12]:
df['InvoiceDate'].min(), df['InvoiceDate'].max()

('1/10/2011 10:04', '9/9/2011 9:52')

In [13]:
df['InvoiceDate'] = pd.to_datetime(
    df['InvoiceDate'],
    format='%m/%d/%Y %H:%M'
)
df['InvoiceDate'].min(), df['InvoiceDate'].max()

(Timestamp('2010-12-01 08:26:00'), Timestamp('2011-12-09 12:50:00'))

In [14]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (536641, 8)

In [15]:
df = df.dropna(subset=['CustomerID'])

print("Shape after removing missing CustomerID:", df.shape)

Shape after removing missing CustomerID: (401604, 8)

In [16]:
df['InvoiceNo'].dtype

In [18]:

df = df[~df['InvoiceNo'].str.startswith('C')]
print("Shape after removing cancelled invoices:", df.shape)

Shape after removing cancelled invoices: (392732, 8)

In [19]:
print("Quantity <= 0:", (df['Quantity'] <= 0).sum())
print("UnitPrice <= 0:", (df['UnitPrice'] <= 0).sum())

Quantity <= 0: 0
UnitPrice <= 0: 40

In [21]:
print("Quantity <= 0 remaining:", (df['Quantity'] <= 0).sum())
print("UnitPrice <= 0 remaining:", (df['UnitPrice'] <= 0).sum())

Quantity <= 0 remaining: 0
UnitPrice <= 0 remaining: 0

In [22]:

df = df[
    (df['Quantity'] > 0) &
    (df['UnitPrice'] > 0)
].copy()

In [23]:
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']
df[['Quantity', 'UnitPrice', 'TotalAmount']].head()

   Quantity  UnitPrice  TotalAmount
0         6       2.55        15.30
1         6       3.39        20.34
2         8       2.75        22.00
3         6       3.39        20.34
4         6       3.39        20.34

In [26]:
df.to_csv('cleaned_online_retail.csv', index=False)